# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for demo
  pod 'IQKeyboardManager'

  pod 'NebPay', :path => '/Users/yuzhou/Workspace/neb.iOS'
  # pod 'NebPay', :git => 'https://github.com/yuzhouwww/neb.iOS.git', :branch => 'develop'
end
